### ISSUE TITLE
How was Figure 1 created?

### ISSUE THREAD

**Issue by daidaiershidi** [samuela/git-re-basin#15]
Thank you for your work. I am quite curious as to how one would obtain a figure like Figure 1.

![image](https://github.com/samuela/git-re-basin/assets/48178838/c4524d03-82ea-49d4-9233-cf1492535ab1)

**Comment by samuela** [comment]
The script that generated that plot is https://github.com/samuela/git-re-basin/blob/main/src/mnist_mlp_loss_contour.py
