### ISSUE TITLE
What license is this code under?

### ISSUE THREAD

**Issue by crowsonkb** [samuela/git-re-basin#9]
We want to modify this code, what license is it/should it be under?

Thank you,
Katherine Crowson

**Comment by samuela** [comment]
Hi Katherine, good question! The code is MIT licensed. I initially neglected to include a LICENSE file, but I just added one in https://github.com/samuela/git-re-basin/commit/16a5645abe7446dca29f25c1e7615a1d0797fd8e 

Thanks for bringing this up!
